### ISSUE TITLE
Не вычитывает значения с типом 30 

### ISSUE THREAD

**Issue by SolarWind13** [MicroKoder/QIEC104#2]
Похоже версия 0.3b имеет некоторые проблемы с вычитыванием данных типа 30 (Single Point with time tag)

Описание "лабораторного" стенда:
- MOXA MGate 5114 в качестве IEC 104 сервера к которой по Modbus (RS-485) подключены:
- Satec PM130EH Plus 
- VKmodule "VRC-I4" (4 дискретных входа) 

Данные с Сатека идут нормально (тип 36), при поставленной галке "Автоматически добавлять тэги" появляются автоматом.
А вот данные о состоянии дискретного  входа (тип 30) никак не хотят - ни автоматически появляться, ни при вручную созданной записи. 

Из-за этого пару дней ломал голову, думая что неправильно настроил МОХА пока не:
- нашёл в МОХА диагностику 104-го сервера и не увидел там что данные нормально формируются
- взял в качестве клиента демо-версию PCVue SCADA, в ней всё замечательно отобразилось.

![moxa_36](https://user-images.githubusercontent.com/35486852/99421666-4db2b780-2907-11eb-9071-2942d6c03f41.png)
![moxa_37](https://user-images.githubusercontent.com/35486852/99421670-4ee3e480-2907-11eb-862e-bc9bad52bbb5.png)
![moxa_38](https://user-images.githubusercontent.com/35486852/99421671-4ee3e480-2907-11eb-9310-fee923a4a700.png)
![moxa_39](https://user-images.githubusercontent.com/35486852/99421673-50151180-2907-11eb-8c7a-65a4b94cd41d.png)

**Comment by SolarWind13** [comment]
Был частично не прав.
Клиент отображает переменную с типом 30 но только если значения этой переменной изменялись во время работы клиента.
Понятно что 104-й - это событийный протокол, отправляющий данные в случае их изменения.
Но как умудрилась PCVue SCADA опросив устройство найти эту переменную?
  
![moxa_40](https://user-images.githubusercontent.com/35486852/99530986-ba32c280-29aa-11eb-895a-e50d58100077.png)

![moxa_41](https://user-images.githubusercontent.com/35486852/99530987-bacb5900-29aa-11eb-9b73-064eb074d7b4.png)

**Comment by MicroKoder** [comment]
Когда добавляете тег вручную то он не опрашивается, надо вызвать контекстное меню сигнала и сделать запрос.
Однако не всегда сервер отвечает на запросы такого типа (когда единичный тег опрашивается).
Другой способ запросить их - сделать общий опрос, это общая команда по которой сервер выдает все что имеет.

**Comment by SolarWind13** [comment]
Не очень понятно о каком контекстном меню идет речь.
В главном окне программы если выбрать строку и нажать ПКМ то в контекстном меню всего один пункт - "Добавить в просмотр"
В окне просмотра если выбрать строку - то по ПКМ только пункт "Удалить"
Общий опрос (нажимал иконку со стрелочками на панели) не помогает.

![moxa11](https://user-images.githubusercontent.com/35486852/99792221-75846400-2b2f-11eb-8e62-c42108879c94.png)

**Comment by SolarWind13** [comment]
И да, кстати. 
Несмотря на то, что скачивал файлик 0.3b если открыть пункт "О программе" то там написано:

> Эмулятор протокла МЭК-104
> GITHUB
> Версия 0.2b

**Comment by SolarWind13** [comment]
Ага, похоже с этим и проблема - как-то я не заметил что есть версии 0.4b и 1.0
Но они что-то у меня не запускаются (OS Win7 64-bit ru)

![moxa12](https://user-images.githubusercontent.com/35486852/99793548-859d4300-2b31-11eb-8fe3-91c5e952fa2c.png)

**Comment by MicroKoder** [comment]
Каюсь. Кривой архив выложил с версией 0.4b. Сейчас обновил. Там же и по ПКМ есть команда "запросить".
Очень странно что по общему опросу сигналы не выдает.

**Comment by MicroKoder** [comment]
Ссылка в описании readme.md, в репозиторий больше не буду складывать релизы

**Comment by MicroKoder** [comment]
Может у вас сервер не отвечает и на общие опросы? Такое бывает например с модулями NOR Shneider electric, там отдельные настройки есть, типа обрабатывать команды общего опроса, обрабатывать запросы и т.п. возможно ваш сервер вообще кроме спорадической передачи ничего не хочет.

**Comment by SolarWind13** [comment]
> 
> 
> Каюсь. Кривой архив выложил с версией 0.4b. Сейчас обновил. Там же и по ПКМ есть команда "запросить".
> Очень странно что по общему опросу сигналы не выдает.

Перекачал, запустилось, кнопка "Запросить" в наличии.
Но данные так и не появляются. :-(
Ни при запросе отдельной строки, ни при общем опросе.

Поскольку MGate 5114 умеет писать дампы обмена, могу попробовать сохранить и предоставить дампы:
- обмена с вашим клиентом
- обмена с PcVue SCADA
если это поможет разобраться в ситуации.

**Comment by SolarWind13** [comment]
> 
> 
> Может у вас сервер не отвечает и на общие опросы? Такое бывает например с модулями NOR Shneider electric, там отдельные настройки есть, типа обрабатывать команды общего опроса, обрабатывать запросы и т.п. возможно ваш сервер вообще кроме спорадической передачи ничего не хочет.

Ок, поизучаю более внимательно настройки MGate 5114 на эту тему.

**Comment by MicroKoder** [comment]
посмотрите что в логе происходит при команде общего опроса. Есть ответ хоть какой нибудь от сервера?

**Comment by SolarWind13** [comment]
> 
> 
> посмотрите что в логе происходит при команде общего опроса. Есть ответ хоть какой нибудь от сервера?

Общий опрос

![moxa13](https://user-images.githubusercontent.com/35486852/99798547-dfa20680-2b39-11eb-8d37-e7f12a2b5a9a.png)

Опрос вручную созданной строки

![moxa14](https://user-images.githubusercontent.com/35486852/99798586-ee88b900-2b39-11eb-9dec-07bc311c2e4a.png)

**Comment by SolarWind13** [comment]
> 
> 
> Может у вас сервер не отвечает и на общие опросы? Такое бывает например с модулями NOR Shneider electric, там отдельные настройки есть, типа обрабатывать команды общего опроса, обрабатывать запросы и т.п. возможно ваш сервер вообще кроме спорадической передачи ничего не хочет.

Настройки IEC104 на MGate 5114

![moxa15](https://user-images.githubusercontent.com/35486852/99798814-517a5000-2b3a-11eb-94c8-789644bb32cd.png)

**Comment by MicroKoder** [comment]
а попробуйте - ка поставить General interrogation timestamp format 56 bits

**Comment by SolarWind13** [comment]
> 
> 
> а попробуйте - ка поставить General interrogation timestamp format 56 bits

Зашибись! Заработало!

![moxa_42](https://user-images.githubusercontent.com/35486852/99824229-1b4ec780-2b5e-11eb-913b-a707416c940e.png)

Данные появляются как после принудительного опроса отдельной строки, так и после общего опроса.
Огромное спасибо, исью можем закрывать :-)

**Comment by MicroKoder** [comment]
не, не совсем. У меня в программе метки времени только 56bits обрабатываются. Надо будет запилить чтоб 24 тоже
