### ISSUE TITLE
Автозагрузка данных.

### ISSUE THREAD

**Issue by SolarWind13** [MicroKoder/QIEC104#3]
Можно ли в перспективе реализовать пару небольших моментов потенциально облегчающих работу с программой:

1. Добавить в опции галочку отвечающую за авто соединение с сервером указанном в настройках?

2. Возможность автоматически загружать сохраненный файл с данными, например запуская программу так:
Q104.exe mydata.dat
Т.е. передавая имя файла с данными как аргумент в командной строке?

**Comment by SolarWind13** [comment]
Да, и похоже в моем случае галочка "Команда опроса при подключении" не срабатывает - с незагруженными данными и автоматическим созданием тэгов весь список тэгов не появляется.
Но если вручную на панели нажать иконку с принудительным опросом - сразу все появляется.

**Comment by MicroKoder** [comment]
сделал автооткрытие файла, пример использования:
Q104.exe E:\base.dat

**Comment by SolarWind13** [comment]
> 
> 
> сделал автооткрытие файла, пример использования:
> **Q104.exe E:\base.dat**
> смотрите версию 0.5b

Подтверждаю, работает.
Теперь бы еще autoconnect при старте... 
Опцией в настройках или через ключ в командной строке.

**Comment by MicroKoder** [comment]
обновил версию 0.5b, автоконнект при старте. 
Также поправил настройки "общий опрос при соединении" и "синхронизация при соединении" а то раньше не работали

**Comment by SolarWind13** [comment]
> 
> 
> обновил версию 0.5b, автоконнект при старте, сделал отдельной настройкой в ini
> Также поправил настройки "общий опрос при соединении" и "синхронизация при соединении" а то раньше не работали

Проверил - работает, спасибо.

Подумал что было бы неплохо добавить ещё одну функцию - восстановление связи при обрыве.
Как добавочные подпункты можно рассмотреть:
- количество попыток соединения
- интервал между попытками соединения.
